name: Deploy Windows VM

trigger:
- main

variables:
  resourceGroupName: 'alex-common-rg'
  vmname: 'alex-vm-devops'
  vmimage: 'Win2022AzureEditionCore'
  vmusername: "azureuser"
  vnet_name: "inf-bastion-vnet"
  subnet_name: "inf-bastion-snet"
  vmpassword: "Azuretest123"
  location: "westeurope"

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureCLI@2
  displayName: Create Windows VM
  inputs:
    azureSubscription: 'ops-di-azuredevops'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az vm create \
          --resource-group $(resourceGroupName) \
          --name $(vmname) \
          --image $(vmimage) \
          --location $(location) \
          --vnet-name $(vnet_name) \
          --subnet $(subnet_name) \
          --admin-username $(vmusername) \
          --admin-password $(vmpassword) \
          --public-ip-address ""